const SITE_CONTENT = {
  meta: {
    name: "Manssuétude",
    tagline: "Penser - Exprimer - Relier<br>Concrétiser - Ancrer",
    brandMark: "M",
    logo: "assets/photos/logo-manssuetude.png",
    favicon: "assets/photos/favicon.png",
    fallbackImage: "assets/photos/hero-a-propos.png",
    percaPhrase: "Penser, exprimer, relier, concrétiser, ancrer.",
    colors: {
      primary: "#ff4d12",
      secondary: "#0d0d0f",
    },
    fonts: {
      heading: "Inter, Arial, Helvetica, sans-serif",
      body: "Inter, Arial, Helvetica, sans-serif",
    },
  },

  nav: [
    { id: "accueil", label: "Accueil", route: "#accueil" },
    { id: "themes", label: "Thèmes", route: "#themes" },
    { id: "activites", label: "Activités", route: "#activites" },
    { id: "productions", label: "Productions", route: "#productions" },
    { id: "projets", label: "Projets", route: "#projets" },
    { id: "perca", label: "PERCA", route: "#perca" },
    { id: "a-propos", label: "À propos", route: "#a-propos" },
    { id: "nous-soutenir", label: "Nous soutenir", route: "#nous-soutenir" },
    { id: "nous-rejoindre", label: "Rejoindre", route: "#nous-rejoindre", cta: true },
    { id: "admin", label: "Admin", route: "#admin", hidden: true },
  ],

  ctaLinks: {
    join: "#nous-rejoindre",
    support: "#nous-soutenir",
    featuredTheme: "#themes/transformation-cemac",
    themes: "#themes",
    productions: "#productions",
    projects: "#projets",
    activities: "#activites",
    resources: "#ressources",
    perca: "#perca",
    about: "#a-propos",
    donate: "FORM:don",
    partner: "FORM:partner",
    moments: "#activites",
    contribution: "FORM:content",
    projectProposal: "FORM:project",
    memberApplication: "FORM:join",
    current: "#accueil",
    formats: "#activites",
    history: "#a-propos",
    impact: "#nous-soutenir",
  },

  footerConfig: {
    description: "Un espace de réflexion, de production, d'expérimentation et de lien pour une jeunesse consciente, libre et ambitieuse.",
    socialLinks: [
      { label: "Facebook", url: "https://facebook.com", short: "f" },
      { label: "Instagram", url: "https://instagram.com", short: "ig" },
      { label: "LinkedIn", url: "https://linkedin.com", short: "in" },
      { label: "YouTube", url: "https://youtube.com", short: "yt" },
    ],
    columns: [
      {
        title: "Explorer",
        links: [
          { label: "Thèmes", url: "#themes" },
          { label: "Activités", url: "#activites" },
          { label: "Productions", url: "#productions" },
          { label: "Projets", url: "#projets" },
          { label: "PERCA", url: "#perca" },
        ],
      },
      {
        title: "Manssuétude",
        links: [
          { label: "À propos", url: "#a-propos" },
          { label: "Notre méthode", url: "#perca" },
          { label: "Nous soutenir", url: "#nous-soutenir" },
          { label: "Rejoindre", url: "#nous-rejoindre" },
        ],
      },
      {
        title: "Ressources",
        links: [
          { label: "Bibliothèque", url: "#productions" },
          { label: "Médiathèque", url: "#ressources" },
          { label: "FAQ", url: "#a-propos" },
          { label: "Admin", url: "#admin" },
        ],
      },
    ],
    newsletterEnabled: true,
    legalLinks: [
      { label: "Contact", url: "#nous-rejoindre" },
      { label: "Mentions légales", url: "#mentions-legales" },
    ],
  },

  homepageConfig: {
    featuredTheme: "theme-cemac",
    featuredProductions: ["prod-industrialisation-cemac", "prod-integration-regionale", "prod-debat-cemac", "prod-jeunes-innovation"],
    featuredProjects: ["project-articles-manssuetude", "project-newsletter-manssuetude"],
    currentItems: ["activity-debat-cemac", "resource-bad-integration", "project-talk-show-manssuetude"],
    showStats: false,
    stats: [
      { icon: "users", value: "0", label: "Chiffre à renseigner" },
      { icon: "message", value: "0", label: "Chiffre à renseigner" },
      { icon: "book", value: "0", label: "Chiffre à renseigner" },
      { icon: "file", value: "0", label: "Chiffre à renseigner" },
      { icon: "community", value: "0", label: "Chiffre à renseigner" },
    ],
    ctaTitle: "Rejoindre une communauté qui pense, produit et expérimente.",
    ctaText: "Manssuétude avance par le collectif : idées solides, formats vivants, productions utiles et liens durables.",
    finalPrimaryCta: "join",
    finalSecondaryCta: "support",
  },

  pageBlocks: {
    method: {
      title: "Notre méthode : PERCA",
      items: [
        { letter: "P", title: "Penser", text: "Prendre du recul, analyser, comprendre les enjeux." },
        { letter: "E", title: "Exprimer", text: "Débattre, partager, affirmer sa pensée." },
        { letter: "R", title: "Relier", text: "Créer des ponts entre les idées et les personnes." },
        { letter: "C", title: "Concrétiser", text: "Transformer les réflexions en projets utiles." },
        { letter: "A", title: "Ancrer", text: "Inscrire les actions dans la durée." },
      ],
    },
    current: {
      eyebrow: "En ce moment chez Manssuétude",
      title: "La réflexion continue.",
      noteTitle: "Nos activités sont guidées par l'impact et la rigueur.",
      notes: [
        "Des sujets ancrés dans les réalités vécues",
        "Des échanges ouverts et exigeants",
        "Des productions au service de l'action",
        "Un collectif engagé et diversifié",
      ],
    },
    approach: {
      eyebrow: "Notre approche",
      title: "Des réflexions profondes, des actions concrètes.",
      text: "Nos thèmes se croisent, s'enrichissent et nourrissent nos débats, productions et projets.",
      items: [
        { title: "Pensée critique", text: "Analyser les réalités avec rigueur et lucidité." },
        { title: "Dialogue ouvert", text: "Débattre sans dogme, écouter pour comprendre." },
        { title: "Solutions ancrées", text: "Proposer des pistes adaptées à nos contextes." },
        { title: "Impact collectif", text: "Construire ensemble pour transformer durablement." },
      ],
    },
    mission: {
      eyebrow: "Notre mission",
      title: "Éclairer les enjeux d'aujourd'hui et agir avec rigueur.",
      cards: [
        { icon: "target", title: "Rigueur", text: "Des analyses solides, des faits vérifiés et une exigence constante." },
        { icon: "users", title: "Ouverture", text: "Des espaces de dialogue pour faire circuler les perspectives." },
        { icon: "heart", title: "Engagement", text: "L'action collective au service d'un impact durable." },
        { icon: "rocket", title: "Ambition", text: "Voir haut pour inspirer et transformer nos sociétés." },
      ],
    },
    timeline: [
      "2021 Naissance de Manssuétude",
      "2022 Premiers ateliers",
      "2023 Structuration de la méthode PERCA",
      "2024 Consolidation du collectif",
      "Aujourd'hui Communauté en évolution",
    ],
    supportWays: [
      { icon: "heart", title: "Faire un don", text: "Financer nos activités, productions et projets.", cta: "Faire un don", ctaKey: "donate" },
      { icon: "handshake", title: "Devenir partenaire", text: "Associer votre organisation a notre vision.", cta: "Devenir partenaire", ctaKey: "partner" },
      { icon: "network", title: "Soutenir en compétences", text: "Mettre vos expertises au service du collectif.", cta: "Contribuer", ctaKey: "contribution" },
      { icon: "megaphone", title: "Faire connaître", text: "Partager Manssuétude autour de vous.", cta: "Partager", ctaKey: "about" },
    ],
    forms: {
      join: {
        title: "Formulaire rejoindre",
        fields: ["Prénom", "Nom", "Email", "Téléphone", "Ville", "Statut", "Centres d'intérêt", "Commission souhaitée", "Motivation", "Disponibilité", "Consentement RGPD"],
      },
      project: {
        title: "Proposer un projet",
        fields: ["Nom", "Email", "Titre du projet", "Description", "Objectif", "Ressources nécessaires", "État d'avancement", "Fichiers joints", "Commission liée"],
      },
      content: {
        title: "Proposer un contenu",
        fields: ["Nom", "Email", "Type de contenu", "Titre", "Résumé", "Fichier joint", "Thème associé"],
      },
      partner: {
        title: "Formulaire partenariat",
        fields: ["Organisation", "Contact", "Email", "Type de partenariat", "Message", "Fichier joint optionnel", "Consentement RGPD"],
      },
      don: {
        title: "Faire un don",
        fields: ["Montant", "Fréquence", "Nom", "Email", "Message optionnel", "Consentement RGPD"],
      },
    },
  },

  pages: {
    accueil: {
      type: "home",
      navLabel: "Accueil",
      eyebrow: "Sujet du moment",
      title: "Transformer structurellement les pays de la CEMAC.",
      accent: "CEMAC",
      body: "Manssuétude est un espace de réflexion, de production et d'expérimentation collective. Nous partons d'un dossier du moment pour apprendre, débattre, produire et créer du lien.",
      image: "assets/photos/hero-accueil.png",
      imageAlt: "Jeunes en discussion autour d'une table de travail",
      quote: "Suivre l'évolution de notre réflexion",
      primary: { label: "Explorer le dossier", ctaKey: "featuredTheme" },
      secondary: { label: "Comprendre notre approche", ctaKey: "perca" },
      sections: [
        { type: "featuredProductions", title: "Productions récentes" },
        { type: "current", title: "En ce moment chez Manssuétude" },
        { type: "method" },
      ],
      seo: {
        title: "Manssuétude - Accueil",
        description: "Un espace de réflexion, de production et d'expérimentation pour une jeunesse consciente, libre et ambitieuse.",
        image: "assets/photos/hero-accueil.png",
        keywords: ["Manssuétude", "CEMAC", "jeunesse", "réflexion"],
      },
    },
    themes: {
      navLabel: "Thèmes",
      eyebrow: "Nos thèmes",
      title: "Explorer les grands dossiers qui nourrissent Manssuétude.",
      accent: "grands dossiers",
      body: "Nos réflexions s'organisent autour de thèmes vivants : on les ouvre, on les documente, on les discute, puis on les transforme en productions, activités ou projets.",
      image: "assets/photos/hero-themes.png",
      imageAlt: "Groupe de jeunes analysant une carte de l'Afrique",
      primary: { label: "Explorer le thème actif", ctaKey: "featuredTheme" },
      secondary: { label: "Proposer un thème", ctaKey: "contribution" },
      sections: [{ type: "themesGrid", title: "Nos grands axes de réflexion" }, { type: "approach" }],
      filters: ["status", "tag"],
      seo: { title: "Thèmes - Manssuétude", description: "Les grands axes de réflexion de Manssuétude.", image: "assets/photos/hero-themes.png", keywords: ["thèmes", "réflexion", "production"] },
    },
    activites: {
      navLabel: "Activités",
      eyebrow: "Nos activités",
      title: "Des formats variés pour penser, débattre et produire ensemble.",
      accent: "agir ensemble",
      body: "Manssuétude n'est pas un agenda figé. Les activités suivent l'énergie du collectif : séances, débats, ateliers, formats médias, expérimentations et ressources préparatoires.",
      image: "assets/photos/hero-activites.png",
      imageAlt: "Séance de travail collective",
      primary: { label: "Découvrir nos thèmes", ctaKey: "featuredTheme" },
      secondary: { label: "Voir nos productions", ctaKey: "productions" },
      stats: [
        { icon: "community", value: "+120", label: "Membres engagés" },
        { icon: "calendar", value: "0", label: "À renseigner" },
        { icon: "users", value: "0", label: "À renseigner" },
        { icon: "globe", value: "0", label: "À renseigner" },
      ],
      sections: [{ type: "activityFormats", title: "Nos formats d'activités" }, { type: "activitiesList", title: "En ce moment chez Manssuétude" }],
      filters: ["format", "progressStatus", "theme"],
      seo: { title: "Activités - Manssuétude", description: "Formats de débats, ateliers et rencontres Manssuétude.", image: "assets/photos/hero-activites.png", keywords: ["activités", "débats", "ateliers"] },
    },
    productions: {
      navLabel: "Productions",
      eyebrow: "Nos productions",
      title: "Des idées partagées, des connaissances pour agir.",
      accent: "pour agir",
      body: "La page Productions est le média Manssuétude : articles, notes, synthèses, carrousels, podcasts, comptes-rendus et ressources pour prolonger les réflexions.",
      image: "assets/photos/hero-productions.png",
      imageAlt: "Document éditorial Manssuétude posé sur une table",
      primary: { label: "Explorer les ressources", ctaKey: "productions" },
      secondary: { label: "Proposer un contenu", ctaKey: "contribution" },
      stats: [
        { icon: "file", value: "35+", label: "Documents publies" },
        { icon: "book", value: "15+", label: "Notes & synthèses" },
        { icon: "chart", value: "10+", label: "Etudes & rapports" },
        { icon: "play", value: "20+", label: "Videos & podcasts" },
        { icon: "download", value: "1000+", label: "Telechargements" },
      ],
      sections: [{ type: "productionsCatalog", title: "Explorer nos contenus" }, { type: "productionCta" }],
      filters: ["type", "theme", "tag", "author"],
      seo: { title: "Productions - Manssuétude", description: "Articles, notes, vidéos, podcasts et rapports Manssuétude.", image: "assets/photos/hero-productions.png", keywords: ["productions", "articles", "rapports"] },
    },
    projets: {
      navLabel: "Projets",
      eyebrow: "Nos projets",
      title: "Transformer les idées en actions concrètes à impact réel.",
      accent: "actions concrètes",
      body: "Les projets Manssuétude peuvent être internes, éditoriaux, méthodologiques, médias ou communautaires. Ils servent à structurer le collectif et à rendre les idées utiles.",
      image: "assets/photos/hero-projets.png",
      imageAlt: "Équipe travaillant sur un projet",
      primary: { label: "Proposer un projet", ctaKey: "projectProposal" },
      secondary: { label: "Voir notre approche", ctaKey: "perca" },
      stats: [
        { icon: "rocket", value: "7", label: "Projets structurants" },
        { icon: "network", value: "15+", label: "Partenaires potentiels" },
        { icon: "target", value: "100%", label: "Alignes sur nos priorites" },
        { icon: "file", value: "3", label: "Formats editoriaux" },
      ],
      sections: [{ type: "projectsCatalog", title: "Tous nos projets" }, { type: "commitments" }],
      filters: ["progressStatus", "category", "priority", "theme"],
      seo: { title: "Projets - Manssuétude", description: "Les projets internes et stratégiques de Manssuétude.", image: "assets/photos/hero-projets.png", keywords: ["projets", "Manssuétude", "impact"] },
    },
    perca: {
      navLabel: "PERCA",
      eyebrow: "PERCA",
      title: "Penser l'Afrique, relier ses energies, construire son avenir.",
      accent: "construire son avenir",
      body: "PERCA n'est pas une entité séparée : c'est le cadre de Manssuétude. Penser, Exprimer, Relier, Concrétiser, Ancrer structurent nos séances, nos productions et nos projets.",
      image: "assets/photos/hero-perca.png",
      imageAlt: "Carte lumineuse de l'Afrique",
      primary: { label: "Decouvrir PERCA", ctaKey: "perca" },
      secondary: { label: "Voir nos initiatives", ctaKey: "projects" },
      stats: [
        { icon: "community", value: "1", label: "Initiative structurante" },
        { icon: "globe", value: "8+", label: "Pays impliques" },
        { icon: "users", value: "100+", label: "Acteurs mobilises" },
        { icon: "flag", value: "4", label: "Grands piliers d'action" },
        { icon: "target", value: "1", label: "Vision commune" },
      ],
      sections: [{ type: "pillars", title: "Les piliers de PERCA" }, { type: "partners", title: "Nos partenaires stratégiques" }],
      seo: { title: "PERCA - Manssuétude", description: "La méthode Manssuétude : penser, exprimer, relier, concrétiser, ancrer.", image: "assets/photos/hero-perca.png", keywords: ["PERCA", "méthode", "Manssuétude"] },
    },
    "a-propos": {
      navLabel: "À propos",
      eyebrow: "À propos de Manssuétude",
      title: "Un espace de réflexion, de production et d'expérimentation collective.",
      accent: "expérimentation collective",
      body: "Manssuétude réunit des jeunes qui veulent penser sérieusement, produire utilement, expérimenter des formats et créer du lien sans perdre leur liberté de ton.",
      image: "assets/photos/hero-a-propos.png",
      imageAlt: "Livre Manssuétude dans une bibliothèque",
      quote: "Nous croyons en la puissance des idées, en la force du collectif et en l'impact des productions concrètes.",
      primary: { label: "Découvrir notre histoire", ctaKey: "history" },
      secondary: { label: "Voir notre impact", ctaKey: "support" },
      sections: [{ type: "mission" }, { type: "timeline" }, { type: "domains", title: "Nos domaines d'action" }],
      seo: { title: "À propos - Manssuétude", description: "Mission, histoire et valeurs de Manssuétude.", image: "assets/photos/hero-a-propos.png", keywords: ["à propos", "mission", "jeunesse"] },
    },
    "nous-soutenir": {
      navLabel: "Nous soutenir",
      eyebrow: "Nous soutenir",
      title: "Soutenez une jeunesse qui pense, agit et construit l'avenir.",
      accent: "construit l'avenir",
      body: "Votre soutien aide Manssuétude à produire, documenter, organiser des espaces de travail et faire circuler des idées exigeantes.",
      image: "assets/photos/hero-nous-soutenir.png",
      imageAlt: "Jeunes se saluant dans un moment collectif",
      primary: { label: "Faire un don", ctaKey: "donate" },
      secondary: { label: "Devenir partenaire", ctaKey: "partner" },
      sections: [{ type: "impact" }, { type: "supportWays", title: "Soutenez-nous de différentes manières" }, { type: "trust" }],
      seo: { title: "Nous soutenir - Manssuétude", description: "Soutenir les activités et productions de Manssuétude.", image: "assets/photos/hero-nous-soutenir.png", keywords: ["soutien", "don", "partenariat"] },
    },
    "nous-rejoindre": {
      navLabel: "Rejoindre",
      eyebrow: "Rejoindre Manssuétude",
      title: "Rejoindre une communauté pour réfléchir, produire, expérimenter et créer du lien.",
      accent: "réfléchir, produire",
      body: "Que vous soyez étudiant, jeune professionnel, créatif, chercheur, entrepreneur ou simplement curieux, il existe plusieurs manières de contribuer à Manssuétude.",
      image: "assets/photos/hero-nous-rejoindre.png",
      imageAlt: "Jeunes reunis autour d'un ordinateur",
      quote: "Ensemble, mettons nos idées, nos talents et notre energie au service d'un impact durable et positif.",
      primary: { label: "Devenir membre", ctaKey: "memberApplication" },
      secondary: { label: "Participer à une activité", ctaKey: "activities" },
      sections: [{ type: "joinWho", title: "Qui peut rejoindre ?" }, { type: "joinSteps", title: "Comment nous rejoindre ?" }],
      seo: { title: "Rejoindre - Manssuétude", description: "Rejoindre la communauté Manssuétude.", image: "assets/photos/hero-nous-rejoindre.png", keywords: ["rejoindre", "communauté", "jeunes"] },
    },
  },

  collections: {
    themes: [
      {
        id: "theme-cemac",
        slug: "transformation-cemac",
        title: "Transformation structurelle des pays de la CEMAC",
        shortTitle: "Transformation CEMAC",
        description: "Industrialisation, souveraineté économique et intégration régionale comme leviers de transformation.",
        longDescription: "Ce theme explore les conditions économiques, institutionnelles, industrielles et humaines permettant aux pays de la CEMAC de passer d'une economie de rente a une dynamique productive, intégrée et souveraine.",
        heroImage: "assets/photos/hero-accueil.png",
        thumbnail: "assets/photos/hero-accueil.png",
        status: "published",
        progressStatus: "active",
        featured: true,
        tags: ["CEMAC", "industrialisation", "intégration régionale", "souveraineté économique"],
        relatedProductions: ["prod-industrialisation-cemac", "prod-integration-regionale", "prod-debat-cemac"],
        relatedProjects: ["project-articles-manssuetude", "project-talk-show-manssuetude"],
        relatedActivities: ["activity-debat-cemac"],
        resources: ["resource-bad-integration"],
      },
      {
        id: "theme-industrie",
        slug: "industrie-souveraineté-économique",
        title: "Industrie & Souverainete économique",
        shortTitle: "Industrie",
        description: "Construire des bases industrielles solides pour une Afrique productive.",
        longDescription: "Un axe pour penser l'industrialisation, les chaines de valeur et la capacite productive locale.",
        heroImage: "assets/photos/card-industrie.png",
        thumbnail: "assets/photos/card-industrie.png",
        status: "published",
        featured: false,
        tags: ["industrie", "production", "souveraineté"],
        relatedProductions: ["prod-industrialisation-cemac"],
        relatedProjects: ["project-articles-manssuetude"],
        relatedActivities: ["activity-atelier-industrie"],
        resources: [],
      },
      {
        id: "theme-integration",
        slug: "integration-regionale-marches",
        title: "Integration régionale & Marches",
        shortTitle: "Integration régionale",
        description: "Renforcer les echanges et harmoniser les politiques économiques.",
        longDescription: "Un theme dedie aux corridors, aux institutions régionales, aux marches communs et aux politiques de cooperation.",
        heroImage: "assets/photos/card-commerce.png",
        thumbnail: "assets/photos/card-commerce.png",
        status: "published",
        featured: false,
        tags: ["intégration", "marches", "commerce"],
        relatedProductions: ["prod-integration-regionale"],
        relatedProjects: ["project-newsletter-manssuetude"],
        relatedActivities: ["activity-debat-cemac"],
        resources: ["resource-bad-integration"],
      },
      {
        id: "theme-transition",
        slug: "transition-ecologique-energie",
        title: "Transition ecologique & Energie",
        shortTitle: "Transition & Energie",
        description: "Penser des modèles de développement durables et résilients.",
        longDescription: "Un theme pour explorer les trajectoires energetiques, les ecosystemes et les solutions adaptees aux realites locales.",
        heroImage: "assets/photos/card-energie.png",
        thumbnail: "assets/photos/card-energie.png",
        status: "published",
        featured: false,
        tags: ["energie", "transition", "durabilite"],
        relatedProductions: ["prod-transition-energie"],
        relatedProjects: ["project-kits-seance"],
        relatedActivities: [],
        resources: [],
      },
      {
        id: "theme-jeunesse",
        slug: "jeunesse-education-capital-humain",
        title: "Jeunesse, Education & Capital humain",
        shortTitle: "Jeunesse & Education",
        description: "Investir dans les compétences, l'education et le leadership.",
        longDescription: "Un axe pour penser la formation, l'engagement, les compétences et la responsabilite d'une jeunesse ambitieuse.",
        heroImage: "assets/photos/hero-activites.png",
        thumbnail: "assets/photos/hero-activites.png",
        status: "published",
        featured: false,
        tags: ["jeunesse", "education", "leadership"],
        relatedProductions: ["prod-jeunes-innovation"],
        relatedProjects: ["project-learning-manssuetude", "project-connect-manssuetude"],
        relatedActivities: ["activity-atelier-industrie"],
        resources: [],
      },
      {
        id: "theme-gouvernance",
        slug: "gouvernance-institutions",
        title: "Gouvernance & Institutions",
        shortTitle: "Gouvernance",
        description: "Promouvoir des institutions fortes, transparentes et efficaces.",
        longDescription: "Un theme autour de la qualité institutionnelle, du bien commun et des conditions politiques de transformation.",
        heroImage: "assets/photos/hero-projets.png",
        thumbnail: "assets/photos/hero-projets.png",
        status: "published",
        featured: false,
        tags: ["gouvernance", "institutions", "transparence"],
        relatedProductions: ["prod-gouvernance"],
        relatedProjects: ["project-articles-manssuetude"],
        relatedActivities: [],
        resources: [],
      },
    ],

    productions: [
      {
        id: "prod-industrialisation-cemac",
        slug: "industrialisation-cemac-ou-en-sommes-nous",
        title: "Industrialisation en CEMAC : ou en sommes-nous ?",
        type: "article",
        description: "Analyse des forces, faiblesses et opportunites industrielles de notre espace regional.",
        content: "Une production de fond pour poser les bases du dossier CEMAC et ouvrir les débats sur la transformation structurelle.",
        contentBlocks: [
          { type: "heading", value: "Comprendre le point de depart" },
          { type: "paragraph", value: "La transformation structurelle suppose de regarder lucidement les capacites productives, les institutions et les chaines de valeur." },
          { type: "quote", value: "Produire, c'est aussi construire de la souveraineté." },
          { type: "file", url: "assets/files/exemple-ressource.txt", label: "Télécharger la note" },
        ],
        date: "2026-05-14",
        author: "Manssuétude",
        thumbnail: "assets/photos/card-industrie.png",
        fileUrl: "assets/files/exemple-ressource.txt",
        readingTime: "7 min",
        pages: "12 pages",
        tags: ["industrie", "CEMAC", "souveraineté économique"],
        relatedThemes: ["theme-cemac", "theme-industrie"],
        relatedProjects: ["project-articles-manssuetude"],
        relatedActivities: ["activity-debat-cemac"],
        featured: true,
        status: "published",
        published: true,
      },
      {
        id: "prod-integration-regionale",
        slug: "integration-regionale-leviers-et-obstacles",
        title: "Integration régionale : leviers et obstacles",
        type: "note",
        description: "Synthese des dynamiques d'intégration en Afrique centrale et perspectives d'acceleration.",
        content: "Une note pour clarifier les obstacles structurels et identifier les leviers de cooperation.",
        contentBlocks: [
          { type: "paragraph", value: "L'intégration régionale ne se decrete pas : elle se construit par des infrastructures, des normes et une confiance politique." },
        ],
        date: "2026-05-10",
        author: "Manssuétude",
        thumbnail: "assets/photos/card-commerce.png",
        fileUrl: "assets/files/exemple-ressource.txt",
        pages: "18 pages",
        tags: ["intégration", "CEMAC", "marches"],
        relatedThemes: ["theme-cemac", "theme-integration"],
        relatedProjects: ["project-newsletter-manssuetude"],
        relatedActivities: ["activity-debat-cemac"],
        featured: true,
        status: "published",
        published: true,
      },
      {
        id: "prod-transition-energie",
        slug: "transition-energetique-afrique-defis-opportunites",
        title: "Transition energetique en Afrique : defis et opportunites",
        type: "rapport",
        description: "Panorama des trajectoires energetiques et des solutions adaptees aux ecosystemes locaux.",
        content: "Une etude introductive pour articuler energie, souveraineté et durabilite.",
        contentBlocks: [{ type: "image", src: "assets/photos/card-energie.png", caption: "Energies renouvelables et trajectoires africaines" }],
        date: "2026-05-08",
        author: "Manssuétude",
        thumbnail: "assets/photos/card-energie.png",
        fileUrl: "assets/files/exemple-ressource.txt",
        pages: "56 pages",
        tags: ["energie", "transition", "Afrique"],
        relatedThemes: ["theme-transition"],
        relatedProjects: ["project-kits-seance"],
        relatedActivities: [],
        featured: true,
        status: "published",
        published: true,
      },
      {
        id: "prod-debat-cemac",
        slug: "debat-quelle-integration-regionale-voulons-nous",
        title: "Débat : Quelle intégration régionale voulons-nous ?",
        type: "video",
        description: "Retour en images sur un debat riche avec experts et jeunes leaders.",
        content: "Un extrait video destine a prolonger la discussion ouverte pendant la seance CEMAC.",
        contentBlocks: [{ type: "video", url: "https://www.youtube.com/embed/dQw4w9WgXcQ", label: "Voir l'extrait video" }],
        date: "2026-05-05",
        author: "Manssuétude",
        thumbnail: "assets/photos/hero-activites.png",
        readingTime: "45 min",
        tags: ["debat", "intégration", "CEMAC"],
        relatedThemes: ["theme-cemac", "theme-integration"],
        relatedProjects: ["project-talk-show-manssuetude"],
        relatedActivities: ["activity-debat-cemac"],
        featured: true,
        status: "published",
        published: true,
      },
      {
        id: "prod-jeunes-innovation",
        slug: "innover-pour-inclure-jeunes-prennent-parole",
        title: "Innover pour inclure : les jeunes prennent la parole",
        type: "podcast",
        description: "Episode avec des entrepreneurs sociaux qui reinventent les solutions locales.",
        content: "Un format audio pour donner la parole aux jeunes porteurs d'initiatives.",
        contentBlocks: [{ type: "paragraph", value: "Le podcast donne a entendre des voix jeunes, situees et ambitieuses." }],
        date: "2026-04-24",
        author: "Manssuétude",
        thumbnail: "assets/photos/hero-a-propos.png",
        readingTime: "32 min",
        tags: ["jeunesse", "innovation", "inclusion"],
        relatedThemes: ["theme-jeunesse"],
        relatedProjects: ["project-talk-show-manssuetude"],
        relatedActivities: [],
        featured: false,
        status: "published",
        published: true,
      },
      {
        id: "prod-gouvernance",
        slug: "gouvernance-afrique-efficacite",
        title: "Gouvernance en Afrique : vers plus d'efficacité ?",
        type: "synthèse",
        description: "Synthese des bonnes pratiques et recommandations pour des institutions performantes.",
        content: "Une synthèse pour nourrir les débats sur la gouvernance et l'action publique.",
        contentBlocks: [{ type: "paragraph", value: "La gouvernance devient un levier de transformation lorsqu'elle organise la confiance et la responsabilite." }],
        date: "2026-04-15",
        author: "Manssuétude",
        thumbnail: "assets/photos/hero-projets.png",
        pages: "14 pages",
        tags: ["gouvernance", "institutions", "efficacité"],
        relatedThemes: ["theme-gouvernance"],
        relatedProjects: ["project-articles-manssuetude"],
        relatedActivities: [],
        featured: false,
        status: "draft",
        published: false,
      },
    ],

    activities: [
      {
        id: "activity-debat-cemac",
        slug: "debat-transformation-cemac",
        title: "Débat collectif sur les scenarios de transformation de la CEMAC",
        format: "debat",
        description: "Un espace de discussion pour confronter les pistes de transformation industrielle, régionale et institutionnelle.",
        date: null,
        progressStatus: "préparation",
        status: "published",
        gallery: ["assets/photos/hero-accueil.png", "assets/photos/hero-activites.png"],
        relatedThemes: ["theme-cemac", "theme-integration"],
        relatedProductions: ["prod-debat-cemac"],
        documents: ["resource-bad-integration"],
        featured: true,
      },
      {
        id: "activity-atelier-industrie",
        slug: "atelier-modeles-industriels-africains",
        title: "Atelier prospectif sur les modèles industriels africains",
        format: "atelier",
        description: "Un atelier de travail pour explorer les modèles industriels adaptes aux contextes africains.",
        date: null,
        progressStatus: "préparation",
        status: "published",
        gallery: ["assets/photos/hero-projets.png"],
        relatedThemes: ["theme-industrie", "theme-jeunesse"],
        relatedProductions: ["prod-industrialisation-cemac"],
        documents: [],
        featured: true,
      },
      {
        id: "activity-learning-session",
        slug: "session-manssuetude-learning",
        title: "Session Manssuétude Learning",
        format: "formation",
        description: "Un format d'apprentissage pour renforcer les compétences d'analyse, d'écriture et de présentation.",
        date: null,
        progressStatus: "en cours",
        status: "draft",
        gallery: ["assets/photos/hero-nous-rejoindre.png"],
        relatedThemes: ["theme-jeunesse"],
        relatedProductions: [],
        documents: [],
        featured: false,
      },
    ],

    projects: [
      {
        id: "project-articles-manssuetude",
        slug: "articles-manssuetude",
        title: "Articles Manssuétude",
        category: "Production intellectuelle",
        status: "published",
        progressStatus: "en cours",
        priority: "stratégique",
        description: "Produire pour chaque theme aborde un article de fond de 9 a 12 pages avec references, publie sur LinkedIn et sur le site, puis adapte en carrousel Instagram.",
        objectives: ["Structurer les idées", "Créer une bibliothèque publique", "Nourrir les débats"],
        commission: "Éditorial",
        deliverables: ["Article long", "Version LinkedIn", "Carrousel Instagram"],
        progress: "Cadre éditorial en construction",
        nextSteps: ["Définir la grille de relecture", "Préparer le prochain dossier"],
        documents: ["resource-template-article"],
        relatedThemes: ["theme-cemac", "theme-industrie", "theme-gouvernance"],
        relatedProductions: ["prod-industrialisation-cemac", "prod-gouvernance"],
        relatedActivities: ["activity-debat-cemac"],
        members: ["Équipe éditorial"],
        partners: [],
        featured: true,
      },
      {
        id: "project-newsletter-manssuetude",
        slug: "newsletter-manssuetude",
        title: "Newsletter Manssuétude",
        category: "Communication éditoriale",
        status: "published",
        progressStatus: "préparation",
        priority: "stratégique",
        description: "Envoyer régulièrement une synthèse des idées, ressources et activités en cours pour garder la communauté reliée.",
        objectives: ["Fidéliser la communauté", "Mettre en avant les productions", "Partager les prochaines pistes"],
        commission: "Communication",
        deliverables: ["Lettre mensuelle", "Sélection de ressources", "Appels à contribution"],
        progress: "Maquette éditoriale à stabiliser",
        nextSteps: ["Choisir le rythme", "Préparer le premier numéro"],
        documents: [],
        relatedThemes: ["theme-integration"],
        relatedProductions: ["prod-integration-regionale"],
        relatedActivities: [],
        members: ["Équipe communication"],
        partners: [],
        featured: true,
      },
      {
        id: "project-kits-seance",
        slug: "kits-de-seance",
        title: "Kits de seance",
        category: "Methodologie",
        status: "published",
        progressStatus: "en cours",
        priority: "stratégique",
        description: "Créer des kits pratiques pour préparer, animer et documenter les séances Manssuétude.",
        objectives: ["Standardiser sans rigidifier", "Faciliter l'animation", "Capitaliser les apprentissages"],
        commission: "Méthode",
        deliverables: ["Kit d'animation", "Trame de compte-rendu", "Checklist séance"],
        progress: "Prototype en cours",
        nextSteps: ["Tester sur une séance", "Améliorer après retour collectif"],
        documents: [],
        relatedThemes: ["theme-transition"],
        relatedProductions: ["prod-transition-energie"],
        relatedActivities: ["activity-atelier-industrie"],
        members: ["Équipe methodologie"],
        partners: [],
        featured: false,
      },
      {
        id: "project-site-web-manssuetude",
        slug: "site-web-manssuetude",
        title: "Site web Manssuétude",
        category: "Plateforme digitale",
        status: "published",
        progressStatus: "en cours",
        priority: "stratégique",
        description: "Construire une plateforme administrable pour publier les contenus, organiser les ressources et rendre visible la dynamique Manssuétude.",
        objectives: ["Centraliser les contenus", "Faciliter l'administration", "Préparer l'évolution vers un CMS"],
        commission: "Digital",
        deliverables: ["Site public", "Console admin", "Médiathèque"],
        progress: "V1 administrable en cours",
        nextSteps: ["Stabiliser l'admin", "Préparer le backend"],
        documents: [],
        relatedThemes: ["theme-jeunesse"],
        relatedProductions: [],
        relatedActivities: [],
        members: ["Équipe digitale"],
        partners: [],
        featured: true,
      },
      {
        id: "project-talk-show-manssuetude",
        slug: "talk-show-manssuetude",
        title: "Talk show Manssuétude",
        category: "Format media",
        status: "published",
        progressStatus: "idée",
        priority: "expérimental",
        description: "Developper un format video ou audio pour faire dialoguer jeunes, experts et praticiens autour des grands enjeux.",
        objectives: ["Faire vivre le débat", "Valoriser les voix jeunes", "Créer des formats courts réutilisables"],
        commission: "Média",
        deliverables: ["Concept émission", "Pilote", "Extraits courts"],
        progress: "Idée à cadrer",
        nextSteps: ["Définir le format", "Identifier les premiers invités"],
        documents: [],
        relatedThemes: ["theme-cemac", "theme-jeunesse"],
        relatedProductions: ["prod-debat-cemac", "prod-jeunes-innovation"],
        relatedActivities: ["activity-debat-cemac"],
        members: ["Équipe media"],
        partners: [],
        featured: false,
      },
      {
        id: "project-learning-manssuetude",
        slug: "manssuetude-learning",
        title: "Manssuétude Learning",
        category: "Formation",
        status: "published",
        progressStatus: "préparation",
        priority: "secondaire",
        description: "Structurer des modules d'apprentissage autour de l'analyse, de l'écriture, de la prise de parole et de l'action collective.",
        objectives: ["Renforcer les compétences", "Former des contributeurs", "Créer des parcours progressifs"],
        commission: "Formation",
        deliverables: ["Modules courts", "Supports de séance", "Parcours contributeur"],
        progress: "Préparation",
        nextSteps: ["Lister les compétences prioritaires", "Construire un premier module"],
        documents: [],
        relatedThemes: ["theme-jeunesse"],
        relatedProductions: [],
        relatedActivities: ["activity-learning-session"],
        members: ["Équipe formation"],
        partners: [],
        featured: false,
      },
      {
        id: "project-connect-manssuetude",
        slug: "manssuetude-connect",
        title: "Manssuétude Connect",
        category: "Communaute",
        status: "published",
        progressStatus: "idée",
        priority: "expérimental",
        description: "Imaginer un dispositif pour relier les membres, les compétences, les opportunites et les projets.",
        objectives: ["Cartographier les talents", "Faciliter les collaborations", "Relier les initiatives"],
        commission: "Communauté",
        deliverables: ["Annuaire interne", "Fiches compétences", "Espaces de mise en relation"],
        progress: "Idée",
        nextSteps: ["Définir les règles de confidentialité", "Tester un format simple"],
        documents: [],
        relatedThemes: ["theme-jeunesse"],
        relatedProductions: [],
        relatedActivities: [],
        members: ["Équipe communauté"],
        partners: [],
        featured: false,
      },
    ],

    resources: [
      {
        id: "resource-bad-integration",
        filename: "rapport-bad-integration.pdf",
        title: "Rapport BAD sur l'intégration régionale en Afrique centrale",
        type: "pdf",
        url: "assets/files/exemple-ressource.txt",
        size: "1.2 Mo",
        uploadedAt: "2026-05-14",
        tags: ["BAD", "intégration", "Afrique centrale"],
        alt: "Rapport d'intégration régionale",
        caption: "Ressource de reference pour nourrir le dossier CEMAC.",
        relatedContent: ["theme-cemac", "prod-integration-regionale", "activity-debat-cemac"],
        status: "published",
        visibility: "public",
        author: "Manssuétude",
      },
      {
        id: "resource-template-article",
        filename: "template-article-manssuetude.docx",
        title: "Template article Manssuétude",
        type: "document",
        url: "assets/files/exemple-ressource.txt",
        size: "240 Ko",
        uploadedAt: "2026-05-14",
        tags: ["template", "article", "edition"],
        alt: "Modele article Manssuétude",
        caption: "Modele interne pour structurer les articles de fond.",
        relatedContent: ["project-articles-manssuetude"],
        status: "draft",
        visibility: "privé",
        author: "Manssuétude",
      },
    ],
    formSubmissions: [],
  },
};
